API_KEY = '4dHM5X0WqHxrZjp0YxJX_dvLCJIljUckJDWsroBX'
SECRET_KEY = 'iZt4EDZWgU-MstPKdvXwA16E9bylraoRQBIT8xhT'
SYMBOL = 'ETH/USD'
POSITION_SIZE = 0.001

# gridbot settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 3

# Per seconds
CHECK_ORDER_FREQUENCY = 2

CLOSED_ORDER_STATUS = 'closed'

